"""rename firebase_uid to supabase_uid

Revision ID: 1771172be9dc
Revises: e8ceab1e88e2
Create Date: 2025-05-14 19:10:17.348689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1771172be9dc'
down_revision: Union[str, None] = 'e8ceab1e88e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('supabase_uid', sa.String(), nullable=True))
    op.drop_index('ix_user_firebase_uid', table_name='user')
    op.create_index(op.f('ix_user_supabase_uid'), 'user', ['supabase_uid'], unique=True)
    op.drop_column('user', 'firebase_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firebase_uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_supabase_uid'), table_name='user')
    op.create_index('ix_user_firebase_uid', 'user', ['firebase_uid'], unique=True)
    op.drop_column('user', 'supabase_uid')
    # ### end Alembic commands ###
